remote_theme: just-the-docs/just-the-docs
title: "Bitcoin Hands-On! 28 “learn-by-doing” exercises to master the basics of managing your own Bitcoin, including wallets, transactions, and self custody "
url: "https://bitcoinhandson.github.io/BitcoinHandsOn/"
baseurl: "/BitcoinHandsOn"
nav_sort: case_insensitive

  docs:
    output: true
    permalink: /:collection/:path/
