title: "Bitcoin, Hands-On!"
remote_theme: just-the-docs/just-the-docs
search_enabled: true


nav:
  - title: "Introduction"
    url: Introduction
  - title: "Exercise 1"
    url: Exercise_1
  - title: "Exercise 2"
    url: Exercise_2
  - title: "Exercise 3"
    url: Exercise_3
  - title: "Exercise 4"
    url: Exercise_4
  - title: "Exercise 5"
    url: Exercise_5
  - title: "Exercise 6"
    url: Exercise_6
  - title: "Exercise 7"
    url: Exercise_7
  - title: "Exercise 9"
    url: Exercise_9
  - title: "Exercise 11"
    url: Exercise_11
  - title: "Exercise 12"
    url: Exercise_12
  - title: "Exercise 13"
    url: Exercise_13
  - title: "Exercise 14"
    url: Exercise_14
  - title: "Exercise 15"
    url: Exercise_15
  - title: "Exercise 16"
    url: Exercise_16
  - title: "Exercise 17"
    url: Exercise_17
  - title: "Exercise 18"
    url: Exercise_18
  - title: "Exercise 19"
    url: Exercise_19
  - title: "Exercise 20"
    url: Exercise_20
  - title: "Exercise 21"
    url: Exercise_21
  - title: "Exercise 22"
    url: Exercise_22
  - title: "Exercise 23"
    url: Exercise_23
  - title: "Exercise 24"
    url: Exercise_24
  - title: "Exercise 25"
    url: Exercise_25
  - title: "Exercise 26"
    url: Exercise_26
  - title: "Exercise 27"
    url: Exercise_27
  - title: "Exercise 28"
    url: Exercise_28
  - title: "Final notes and next steps"
    url: Final_notes_and_next_steps
  - title: "Resources"
    url: Resources
